<?xml version = '1.0' encoding = 'iso-8859-1'?>
<!-- Author  : S.ROKKANEN/RO2K - 18/06/2016 -->
<!-- Version : 1.0 -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="text" encoding="iso-8859-1"/>
  <xsl:param name="filename"/>
  <xsl:param name="xslTemplate"/>
  <xsl:param name="xmlModel"/>
  <xsl:template name="header">
    <xsl:param name="xslTemplate"/>
    <xsl:param name="filename"/>//------------------------------------------------------------------------------
// <auto-generated>
//     <xsl:value-of select='$filename'/>  
//     This code was generated from a XSL template:
//          (<xsl:value-of select='$xmlModel'/>) ---> Transform(NovaDesk.Model\_Generator\Template\<xsl:value-of select='$xslTemplate'/>) ---> Code
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.  
// </auto-generated>
//------------------------------------------------------------------------------  
</xsl:template>
</xsl:stylesheet>
